#120 おすすめ記事の評価関数を変更
OUCC/oucc.github.io pull request #121
Opened 2024-04-21 07:28 UTC by miyaji255

以下の基準で実装しました
- タグが一致する +1
- 記事カテゴリが一致する +2
- 同順位内では新しい順

2024-04-27 09:36 UTC, aiueo-1234 requested changes

2024-04-27 09:36 UTC, aiueo-1234 commented on src/content/_blog-statistics.ts
>    return id === undefined ? tagStatistics : tagStatistics[id]
念のため条件に`|| id === null`も追加してください

2024-04-27 10:36 UTC, miyaji255 commented on src/content/_blog-statistics.ts
>    return id === undefined ? tagStatistics : tagStatistics[id]
引数にnullを入れられないので大丈夫だと思います

2024-04-28 19:02 UTC, aiueo-1234 approved these changes
LGTM

2024-04-28 21:20 UTC, merged