WIP
OUCC/oucc.github.io pull request #57
Opened 2023-12-07 11:12 UTC by ciffelia

2023-12-07 14:39 UTC, miyaji255 requested changes
何故かOGPが表示されないです。おそらく拡張子が必要なのだと思います。

また、特にタグのアイコンは2~3色のものが多くjpegよりpngのほうがいいと考えたのですが、やはりjpegのほうが良いですか？

2023-12-07 15:18 UTC, ciffelia commented
> 何故かOGPが表示されないです。おそらく拡張子が必要なのだと思います。

こちらでは拡張子がついており表示されるように見えるのですが、どのページでしょうか？

> また、特にタグのアイコンは2~3色のものが多くjpegよりpngのほうがいいと考えたのですが、やはりjpegのほうが良いですか？

たしかにタグのアイコンはPNGで問題なさそうなのでそうします。

2023-12-07 23:30 UTC, miyaji255 commented
ogpのパスを直接指定してブラウザで見る分には問題ないですが、下に示すような拡張機能を用いてogpを表示するテストをしてみると少なくともdiscordでは表示されません。また、ogpのパスにビルド時のパスがそのまま見えているのも良くないと思います。

https://chromewebstore.google.com/detail/localhost-ogp-%E3%83%81%E3%82%A7%E3%83%83%E3%82%AB%E3%83%BC/gcbnmkhkglonipggglncobhklaegphgn?hl=ja

2023-12-08 10:59 UTC, miyaji255 commented
> 何故かOGPが表示されないです。おそらく拡張子が必要なのだと思います。

すみません。これは`astro dev`だけでした。

2023-12-08 10:59 UTC, miyaji255 approved these changes

2023-12-08 14:40 UTC, merged